name: Build and Deploy

# Only run when a push happens to the main branch
on:
  push:
    branches:
      - main

# Define jobs
jobs:

  # Build the Docker image and deploy it to Docker Hub
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and Deploy to Docker Hub
      # Define environment variables for Docker Hub credentials
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        # Log in to Docker Hub
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        # Build Docker image with a tag
        docker build -t $DOCKER_USERNAME/ice-cream-shop .
        # Push the Docker image to Docker Hub
        docker push $DOCKER_USERNAME/ice-cream-shop:latest

